# Generated by Django 3.2.8 on 2021-10-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('price', models.PositiveIntegerField()),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='static/uploads')),
                ('description', models.CharField(max_length=1000)),
                ('object_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='search',
            name='search',
            field=models.CharField(max_length=300),
        ),
    ]
