# Generated by Django 3.2.8 on 2021-10-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_website', '0002_auto_20211008_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='object_type',
        ),
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_type',
            field=models.CharField(choices=[('G', 'General'), ('VG', 'Vegetables'), ('FT', 'Fruits'), ('GR', 'Groceries'), ('HG', 'Hygiene'), ('GR', 'Grooming'), ('CL', 'Clothing')], default='G', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
